		<!--begin:: Global Optional Vendors -->
		<script src="<?= themes_url('general') ?>/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/block-ui/jquery.blockUI.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/bootstrap-datepicker/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/bootstrap-timepicker/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/bootstrap-switch/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/select2/dist/js/select2.full.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/handlebars/dist/handlebars.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/nouislider/distribute/nouislider.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/autosize/dist/autosize.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/dropzone/dist/dropzone.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/summernote/dist/summernote.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/markdown/lib/markdown.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/bootstrap-markdown/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/bootstrap-notify/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/jquery-validation/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/toastr/build/toastr.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/raphael/raphael.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/morris.js/morris.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/vendors/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/counterup/jquery.counterup.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
		<script src="<?= themes_url('custom') ?>/components/vendors/sweetalert2/init.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/jquery.repeater/src/lib.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/jquery.repeater/src/repeater.js" type="text/javascript"></script>
		<script src="<?= themes_url('general') ?>/dompurify/dist/purify.js" type="text/javascript"></script>
